package/mash-client.spec

Gzip the man pages to reduce package size.

Add requires to buildrequires.

---

mash_client/cli.py

Azure requires source storage info (ARM) and destination info (ASM).

Handle azure storage source and destination.

---

mash_client/cli.py
mash_client/cli_utils.py

Use required options instead of positional args.

---

mash_client/cli.py

- Add comments and make job-id an option.
- Update help text and docstring for base MASH command.

Update mash job delete.

---

mash_client/cli.py
mash_client/cli_utils.py

Make args required options and update docstring + help text.

Update account delete.

---

.travis.yml
mash_client/cli_utils.py
requirements-dev.txt
setup.cfg
setup.py
tests/cassettes/account_add_azure.yml
tests/cassettes/account_add_ec2.yml
tests/cassettes/account_add_gce.yml
tests/cassettes/account_delete.yml
tests/cassettes/job_add.yml
tests/cassettes/job_add_invalid.yml
tests/cassettes/job_delete.yml
tests/data/.config
tests/data/azure_creds.json
tests/data/gce_creds.json
tests/data/invalid_job.json
tests/data/job.json
tests/test_mash_client_cli.py

- Add travis testing config.
- Update testing requirements and add support for python3.7.
- Add vcrpy integration tests and cassette recordings.
- Raise MashClientException instead of Exception.

Add integration test suite

---

mash_client/cli.py
tests/cassettes/account_add_azure.yml
tests/cassettes/account_add_ec2.yml
tests/cassettes/account_add_gce.yml
tests/cassettes/account_delete.yml
tests/cassettes/job_add.yml
tests/cassettes/job_add_invalid.yml
tests/data/invalid_job.json
tests/data/job.json

Use cloud, clouds and cloud framework instead.

Remove references to provider.

---

man/man1/mash.1
mash_client/cli.py
mash_client/cli_utils.py

Dir is specific to client instead of just mash.

Move default mash client config file.

---

mash_client/cli.py
tests/cassettes/account_add_ec2.yml
tests/test_mash_client_cli.py

Instead of a target region list.

Add ec2 account has a single target region.

---

mash_client/cli.py

Re-word cli option help messages.

---

mash_client/cli_utils.py

- Echo dictionary pretty print style to terminal.
- Remove unused max key function.

Simplify echo dictionary function.

---

mash_client/cli_utils.py
requirements.txt

- Update error handling in handle_request.
- Return json data if request is successful.
- Add function to handle requests with tokens, if access token is expired attempt to refresh tokens automatically.
- Add functinos to handle refresh tokens, and get/save tokens to file.

Add token option to handle request function.

---

mash_client/cli_utils.py

Used by delete functions if user enters N for prompt response.

Add function to abort cli.

---

mash_client/cli/__init__.py
mash_client/cli/user.py
tests/test_user.py

Provides endpoints to get, create and delete mash users.

Add endpoints for mash user handling.

---

mash_client/cli/account/__init__.py
mash_client/cli/account/azure.py
tests/test_azure_account.py

Provides CrUD, get and list for azure accounts.

Add endpoints for azure accounts.

---

mash_client/cli/account/__init__.py
mash_client/cli/account/gce.py
tests/test_gce_account.py

Provides CrUD, get and list for gce accounts.

Add endpoints for gce accounts.

---

mash_client/cli/__init__.py
mash_client/cli/auth/__init__.py
tests/test_auth_cli.py

Provides login and logout of mash users.

Add endpoints for authorization.

---

mash_client/cli/account/__init__.py
mash_client/cli/account/ec2.py
mash_client/cli_utils.py
tests/test_ec2_account.py

Provides CrUD, get and list for ec2 accounts.

Add endpoints for ec2 accounts.

---

mash_client/cli_utils.py

If the wrong server is setup in config it may not return a json
response. Provide useful error message and prevent throwing json
decode error.

Better handle connection and 404 errors.

---

mash_client/cli/auth/__init__.py
mash_client/cli/auth/token.py
tests/test_token.py

For handling get, list, delete and refresh of authentication tokens.

Add token endpoints.

---

mash_client/cli/job/__init__.py
mash_client/cli/job/azure.py
mash_client/cli/job/ec2.py
mash_client/cli/job/gce.py
tests/test_azure_job.py
tests/test_ec2_job.py
tests/test_gce_job.py

Add job endpoints for azure, ec2 and gce.

Add endpoints for adding jobs.

---

mash_client/cli/account/azure.py
mash_client/cli/account/ec2.py
mash_client/cli/account/gce.py

Prevent unnecessary redirects when requesting account lists.

Fix account list routes.

---

docs/source/config.rst

Add info on profile option to docs and update --config-dir option.

Update the configuration docs with profile.

---

mash_client/cli/auth/__init__.py
mash_client/cli_utils.py
tests/test_auth_cli.py
tests/test_cli_utils.py

Client side implementation of OAuth2 OpenID Connect authentication. See https://github.com/SUSE-Enceladus/mash/pull/627 for server side implementation and more information.

OpenID Connect authentication support

---

mash_client/cli/user.py
mash_client/cli_utils.py
tests/data/default.yaml
tests/test_user.py

Used for password based logins to Mash server.

Add commands for password change and reset.

---

mash_client/cli/config.py

+ Show the default config directory in the prompt
+ Create the config directory if it does not exists
+ Support the use of "~" as shortcut to the home directory

- Improvements to config file setup

---

mash_client/cli_utils.py

Ensure server is closed after shutdown.
Follow up to last PR. Set DIV color based on success.

Add border on div and change color on status.

---

mash_client/cli/account/azure.py
tests/test_azure_account.py

Drop destination fields for Azure accounts.

---

mash_client/cli/account/aliyun.py
mash_client/cli/account/azure.py
mash_client/cli/account/ec2.py
mash_client/cli/account/gce.py
mash_client/cli/account/oci.py
mash_client/cli/auth/__init__.py
mash_client/cli/auth/token.py
mash_client/cli/job/__init__.py
mash_client/cli/job/aliyun.py
mash_client/cli/job/azure.py
mash_client/cli/job/ec2.py
mash_client/cli/job/gce.py
mash_client/cli/job/oci.py
mash_client/cli/user.py
mash_client/cli_utils.py
mash_client/controller.py

All routes updated to v1. Job add and list routes have a version config option.

Handle versioning in routes.

---

mash_client/cli_utils.py
tests/test_aliyun_account.py
tests/test_aliyun_job.py
tests/test_azure_account.py
tests/test_azure_job.py
tests/test_ec2_account.py
tests/test_ec2_job.py
tests/test_gce_account.py
tests/test_gce_job.py
tests/test_job.py
tests/test_oci_account.py
tests/test_oci_job.py
tests/test_token.py
tests/test_user.py

This limits the chances of race condition where token expires
between checking expiration and the actual request.
Fixes #83

Add a small buffer when checking token expiration.

---

package/mash-client.spec

Use explicit python311 requirements
